name: tests-payments

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd services/payments
          touch .env
          echo STRIPE_SECRET=${{ STRIPE_SECRET }} >> .env
          echo STRIPE_WEBHOOK_SECRET=${{ STRIPE_WEBHOOK_SECRET }} >> .env
          npm install
          npm run test:ci
